export default {
    SIGN_UP_IN_BEGIN: 'SIGN_UP_IN_BEGIN',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_IN_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_IN_ERROR: 'SIGN_UP_IN_ERROR',
    SIGN_OUT: 'SIGN_OUT'
}